### ISSUE TITLE
no opam package available for ocaml 4.03 and 4.04

### ISSUE THREAD

**Issue by gruenewa** [akabe/ppx_bigarray#2]
Hi,

I think ppx_bigarray is a very cool idea. Could you please publish opam packages for ocaml 4.03 and 4.04? Currently these platforms give the following error message:

$ opam install ppx_bigarray
[ERROR] ppx_bigarray is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.03.0".

**Comment by akabe** [comment]
OK. I'll release ppx_bigarray for ocaml 4.03 or above soon.

**Comment by akabe** [comment]
Released v2.0.0: https://github.com/akabe/ppx_bigarray/releases/tag/v2.0.0 (supported OCaml 4.03 or above)
The opam package of ppx_bigarray 2.0.0 will be published (https://github.com/ocaml/opam-repository/pull/7856).

**Comment by gruenewa** [comment]
Thank you very much!
